### ISSUE TITLE
Optional Routes

### ISSUE THREAD

**Issue by dragoonis** [conferencetools/tickets-module#32]
I don't want to routes to auto-kick-in. I want the code that's in here but want the flexibility to configure my own routes.

**Comment by tdutrion** [comment]
Is this only a documentation problem?

You can override routes in a file pretty easily, but maybe there are routes you may not want, is this the actual problem?

**Comment by carnage** [comment]
The routes can be customised using standard Zend config, this has now been documented: https://conferencetools.github.io/docs/tickets/configuration/
