### ISSUE TITLE
pwgen System requirement

### ISSUE THREAD

**Issue by tdutrion** [conferencetools/tickets-module#44]
While it's not explicited in the documentation, there is a requirement on having pwgen installed and available on the install machine.

Solutions offered:
* update README
* use [derq3k/docker-pwgen](https://hub.docker.com/r/derq3k/docker-pwgen/)

Not sure which one is the best...

**Comment by carnage** [comment]
I've updated the readme for now. Will leave this open and see if I can come up with a better solution.

**Comment by carnage** [comment]
Closed as no longer relevant to this repo
